# Generated by Django 5.0.7 on 2024-07-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at']},
        ),
    ]
