# Generated by Django 5.0.7 on 2024-07-25 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_buyer_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='store.company'),
            preserve_default=False,
        ),
    ]
